notifications:
  email:
    recipients:
      - 297442500@qq.com
  on_success: change
  on_failure: always

language: java

jdk:
    - oraclejdk8


script:
  - mvn clean install -U -Dmaven.test.skip=true

 